# Lab10 프로그래밍 과제

아래의 코드는 jupyter notebook이 돌아가는 환경상에 라이브러리를 설치하는 코드입니다. 아래의 import 문에서 문제가 발생하거나 실행중 커널이 오류를 발생하며 실행 중지된다면 아래의 주석을 해제하여 실행해보는 것을 권장합니다.

주석 해제 후 실행했을 때 정상적으로 설치가 되거나 Requirement already satisfied 메시지가 출력된다면 문제가 발생한것이 아닙니다.

In [1]:
# !pip install torch
# !pip install torchvision
# !pip install -U numpy
# !pip install -U matplotlib

In [2]:
import torch

ModuleNotFoundError: No module named 'torch'

In [ ]:
def validation(tensor1, tensor2):
    if None in [tensor1, tensor2]:
        print('\033[31m' + "Variable with None value was entered")
        return
    elif list in [type(tensor1), type(tensor2)]:
        tensor1 = torch.Tensor(tensor1)
        tensor2 = torch.Tensor(tensor2)
    elif tensor1.shape != tensor2.shape:
        print('\033[31m' + "Different shape", tensor1.shape, tensor2.shape)
        return

    if torch.all(torch.isclose(tensor1, tensor2)):
        print('\033[94m' + "Two tensors are identical")
    else:
        print('\033[31m' + "Something wrong..")

# Problem 1 (4 points)

## Problem 1-1 (2 points): Einstein Summation을 이용하여 torch.matmul과 같은 계산결과를 반환하는 코드를 작성하시오.

In [ ]:
A = torch.arange(32.).reshape(8, 4)
B = torch.arange(16.).reshape(4, 4)
print('mat1 :\n', A)
print('mat2 :\n', B)

mat1 :
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.],
        [20., 21., 22., 23.],
        [24., 25., 26., 27.],
        [28., 29., 30., 31.]])
mat2 :
 tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])


In [ ]:
C_answer = torch.matmul(A, B)
print('Multiplication result :\n',C_answer)

Multiplication result :
 tensor([[  56.,   62.,   68.,   74.],
        [ 152.,  174.,  196.,  218.],
        [ 248.,  286.,  324.,  362.],
        [ 344.,  398.,  452.,  506.],
        [ 440.,  510.,  580.,  650.],
        [ 536.,  622.,  708.,  794.],
        [ 632.,  734.,  836.,  938.],
        [ 728.,  846.,  964., 1082.]])


In [ ]:
# your code here
C_einsum =torch.einsum("ij,jk->ik",A,B)

In [ ]:
print("Einsum Matmul result:\n",C_einsum)
validation(C_answer, C_einsum)

Einsum Matmul result:
 tensor([[  56.,   62.,   68.,   74.],
        [ 152.,  174.,  196.,  218.],
        [ 248.,  286.,  324.,  362.],
        [ 344.,  398.,  452.,  506.],
        [ 440.,  510.,  580.,  650.],
        [ 536.,  622.,  708.,  794.],
        [ 632.,  734.,  836.,  938.],
        [ 728.,  846.,  964., 1082.]])
Two tensors are identical


## Problem 1-2 (2 points): Einstein Summation을 이용하여 Hadamard product를 수행하는 코드를 작성하시오.

In [ ]:
A = torch.arange(30).reshape(6, 5)
B = torch.arange(30).reshape(6, 5)

print(A)
print(B)

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]])


In [ ]:
C_answer = torch.mul(A, B)
print(C_answer)

tensor([[  0,   1,   4,   9,  16],
        [ 25,  36,  49,  64,  81],
        [100, 121, 144, 169, 196],
        [225, 256, 289, 324, 361],
        [400, 441, 484, 529, 576],
        [625, 676, 729, 784, 841]])


In [ ]:
#your code here
C_einsum = torch.einsum("ij,ij->ij",A,B)

In [ ]:
print("Einsum Matmul result:\n",C_einsum)
validation(C_answer, C_einsum)

Einsum Matmul result:
 tensor([[  0,   1,   4,   9,  16],
        [ 25,  36,  49,  64,  81],
        [100, 121, 144, 169, 196],
        [225, 256, 289, 324, 361],
        [400, 441, 484, 529, 576],
        [625, 676, 729, 784, 841]])
Two tensors are identical


# Problem 2 (6 points) : 각 문항별 수식에 해당하는 계산을 einsum을 이용하여 수행하시오

 ## Problem 2-1 (3 points)

\begin{align}
    A = [a_{ijk}] \in \mathbb{R}^{I\times J\times K}이고\newline
    B = [b_{jil}] \in \mathbb{R}^{J\times l \times L}일때\newline
    C = [c_{k, l}] \in \mathbb{R}^{K \times L},\newline
    c_{k, l} = \displaystyle\sum_{i = 0}^{I-1} \displaystyle\sum_{j = 0}^{J-1}{a_{i,j,k} \times b_{j, i, l}}\newline
\end{align}
을 만족하는 행렬 C의 계산을 einsum을 이용하여 수행하시오

In [ ]:
A = torch.arange(60.).reshape(3, 4, 5)
B = torch.arange(24.).reshape(4, 3, 2)
print(A)
print(B)

tensor([[[ 0.,  1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.,  9.],
         [10., 11., 12., 13., 14.],
         [15., 16., 17., 18., 19.]],

        [[20., 21., 22., 23., 24.],
         [25., 26., 27., 28., 29.],
         [30., 31., 32., 33., 34.],
         [35., 36., 37., 38., 39.]],

        [[40., 41., 42., 43., 44.],
         [45., 46., 47., 48., 49.],
         [50., 51., 52., 53., 54.],
         [55., 56., 57., 58., 59.]]])
tensor([[[ 0.,  1.],
         [ 2.,  3.],
         [ 4.,  5.]],

        [[ 6.,  7.],
         [ 8.,  9.],
         [10., 11.]],

        [[12., 13.],
         [14., 15.],
         [16., 17.]],

        [[18., 19.],
         [20., 21.],
         [22., 23.]]])


In [ ]:
C_answer = torch.sum(torch.bmm(A.permute(1, 2, 0), B), axis=0)
print(C_answer)

tensor([[4400., 4730.],
        [4532., 4874.],
        [4664., 5018.],
        [4796., 5162.],
        [4928., 5306.]])


In [ ]:
#your code here
C_einsum =torch.torch.einsum('ijk,jil->kl',A,B)

In [ ]:
print(C_einsum)
validation(C_answer, C_einsum)

tensor([[4400., 4730.],
        [4532., 4874.],
        [4664., 5018.],
        [4796., 5162.],
        [4928., 5306.]])
Two tensors are identical


## Problem 2-2 (3 points)

\begin{align}
    A = [a_{bik}] \in \mathbb{R}^{B\times I\times K}이고\newline
    B = [b_{bkj}] \in \mathbb{R}^{B\times K\times J} 일 때\newline
    C = [c_{bij}] \in \mathbb{R}^{B\times I\times J},\newline
    c_{bij} = \displaystyle\sum_{k = 0}^{K-1}{a_{bik}}{b_{bkj}}
\end{align}

In [ ]:
A = torch.arange(800.).reshape(32, 5, 5)/800.0
B = torch.arange(320.).reshape(32, 5, 2)/320.0
print(A)
print(B)

tensor([[[0.0000, 0.0012, 0.0025, 0.0037, 0.0050],
         [0.0063, 0.0075, 0.0088, 0.0100, 0.0113],
         [0.0125, 0.0137, 0.0150, 0.0162, 0.0175],
         [0.0188, 0.0200, 0.0213, 0.0225, 0.0237],
         [0.0250, 0.0262, 0.0275, 0.0288, 0.0300]],

        [[0.0312, 0.0325, 0.0338, 0.0350, 0.0362],
         [0.0375, 0.0388, 0.0400, 0.0413, 0.0425],
         [0.0437, 0.0450, 0.0463, 0.0475, 0.0487],
         [0.0500, 0.0512, 0.0525, 0.0538, 0.0550],
         [0.0562, 0.0575, 0.0587, 0.0600, 0.0613]],

        [[0.0625, 0.0637, 0.0650, 0.0662, 0.0675],
         [0.0688, 0.0700, 0.0712, 0.0725, 0.0737],
         [0.0750, 0.0763, 0.0775, 0.0787, 0.0800],
         [0.0812, 0.0825, 0.0838, 0.0850, 0.0862],
         [0.0875, 0.0887, 0.0900, 0.0913, 0.0925]],

        [[0.0938, 0.0950, 0.0962, 0.0975, 0.0988],
         [0.1000, 0.1013, 0.1025, 0.1037, 0.1050],
         [0.1063, 0.1075, 0.1088, 0.1100, 0.1112],
         [0.1125, 0.1138, 0.1150, 0.1163, 0.1175],
         [0.1187, 0.1200,

In [ ]:
C_answer = torch.bmm(A, B)
print(C_answer)

tensor([[[2.3438e-04, 2.7344e-04],
         [6.2500e-04, 7.6172e-04],
         [1.0156e-03, 1.2500e-03],
         [1.4063e-03, 1.7383e-03],
         [1.7969e-03, 2.2266e-03]],

        [[7.4609e-03, 7.9883e-03],
         [8.8281e-03, 9.4531e-03],
         [1.0195e-02, 1.0918e-02],
         [1.1563e-02, 1.2383e-02],
         [1.2930e-02, 1.3848e-02]],

        [[2.4453e-02, 2.5469e-02],
         [2.6797e-02, 2.7910e-02],
         [2.9141e-02, 3.0352e-02],
         [3.1484e-02, 3.2793e-02],
         [3.3828e-02, 3.5234e-02]],

        [[5.1211e-02, 5.2715e-02],
         [5.4531e-02, 5.6133e-02],
         [5.7852e-02, 5.9551e-02],
         [6.1172e-02, 6.2969e-02],
         [6.4492e-02, 6.6387e-02]],

        [[8.7734e-02, 8.9727e-02],
         [9.2031e-02, 9.4121e-02],
         [9.6328e-02, 9.8516e-02],
         [1.0063e-01, 1.0291e-01],
         [1.0492e-01, 1.0730e-01]],

        [[1.3402e-01, 1.3650e-01],
         [1.3930e-01, 1.4187e-01],
         [1.4457e-01, 1.4725e-01],
         [

In [ ]:
#your code here
C_einsum =torch.einsum('bik,bkj->bij',A,B)

In [ ]:
print(C_einsum)
validation(C_answer, C_einsum)

tensor([[[2.3438e-04, 2.7344e-04],
         [6.2500e-04, 7.6172e-04],
         [1.0156e-03, 1.2500e-03],
         [1.4063e-03, 1.7383e-03],
         [1.7969e-03, 2.2266e-03]],

        [[7.4609e-03, 7.9883e-03],
         [8.8281e-03, 9.4531e-03],
         [1.0195e-02, 1.0918e-02],
         [1.1563e-02, 1.2383e-02],
         [1.2930e-02, 1.3848e-02]],

        [[2.4453e-02, 2.5469e-02],
         [2.6797e-02, 2.7910e-02],
         [2.9141e-02, 3.0352e-02],
         [3.1484e-02, 3.2793e-02],
         [3.3828e-02, 3.5234e-02]],

        [[5.1211e-02, 5.2715e-02],
         [5.4531e-02, 5.6133e-02],
         [5.7852e-02, 5.9551e-02],
         [6.1172e-02, 6.2969e-02],
         [6.4492e-02, 6.6387e-02]],

        [[8.7734e-02, 8.9727e-02],
         [9.2031e-02, 9.4121e-02],
         [9.6328e-02, 9.8516e-02],
         [1.0063e-01, 1.0291e-01],
         [1.0492e-01, 1.0730e-01]],

        [[1.3402e-01, 1.3650e-01],
         [1.3930e-01, 1.4187e-01],
         [1.4457e-01, 1.4725e-01],
         [