# Lab 8 프로그래밍 과제

In [1]:
import numpy as np

# Problem 1 (4 points)

In [2]:
array_a = np.arange(0,100)
print(array_a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


NumPy의 np.sum()함수를 이용하여 배열안에 모든 원소들의 합을 구함.

In [3]:
sum_array = np.sum(array_a)
print("Sum of all elements in array_a: ", sum_array)

Sum of all elements in array_a:  4950


NumPy의 array_a 배열을 Python의 기본 list_a 리스트로 변환

In [4]:
list_a = array_a.tolist()
print(list_a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


## Problem 1-1: Python의 리스트 list_a 를 이용하여 np.sum(array_a)과 같은 계산을 수행하는 total_sum() 함수를 작성하시오.

In [6]:
"""
이 셀 안에 코드를 작성하시오.
"""
# 함수 작성
def total_sum(a):
  sum=0
  for i in a:
    sum+=i
  return sum
    # your code here


위에 구현한 total_sum() 함수를 호출하여 반환된 결과값(sum_list)을 출력함.

In [7]:
# 함수 호출
sum_list = total_sum(list_a)        
# 결과 출력
print("Sum of all elements in list_a: ", sum_list)

Sum of all elements in list_a:  4950



NumPy 배열 array_a의 형태를 reshape()를 이용하여 변환하고 array_b에 할당함.

In [8]:
array_b = array_a.reshape(5,20)
print(array_b)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


NumPy의 np.sum()함수를 이용하여 각각의 열 별로 합을 구함.

In [9]:
column_sum_array = np.sum(array_b, axis=0)
print("Column sum of array_b: ", column_sum_array)

Column sum of array_b:  [200 205 210 215 220 225 230 235 240 245 250 255 260 265 270 275 280 285
 290 295]


## Problem 1-2: Python의 리스트 list_b 를 이용하여 위의 np.sum(array_b, axis=0)과 같은 계산을 수행하는 column_sum() 함수를 작성하시오.

NumPy의 array_b 배열을 Python의 기본 list_b 리스트로 변환

In [11]:
list_b = array_b.tolist()
print(len(list_b[1]))
print(list_b)

20
[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19], [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39], [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59], [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79], [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]


In [19]:
"""
이 셀 안에 코드를 작성하시오.
"""
# 함수 작성
def column_sum(b):
  a=[]
  for i in range(len(b[1])):
    sum=0
    for k in range(len(b)):
      sum +=int(b[k][i])
    a.append(sum)
  return a
    # your code here


위에 구현한 column_sum() 함수를 호출하여 반환된 결과값을 출력함.

In [20]:
# 함수 호출
column_sum_list = column_sum(list_b)
# 결과 출력
print("Column sum of list_b: ", column_sum_list)

Column sum of list_b:  [200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255, 260, 265, 270, 275, 280, 285, 290, 295]


NumPy의 np.sum()함수를 이용하여 각각의 행 별로 합을 구함.

In [16]:
row_sum_array = np.sum(array_b, axis=1)
print("Row sum of array_b: ", row_sum_array)

Row sum of array_b:  [ 190  590  990 1390 1790]


## Problem 1-3: Python의 리스트 list_b 를 이용하여 위의 np.sum(array_b, axis=1)과 같은 계산을 수행하는 row_sum() 함수를 작성하시오.

In [22]:
"""
이 셀 안에 코드를 작성하시오.
"""
# 함수 작성
def row_sum(b):
  a=[0 for j in range(len(b))]
  for i in range(len(b)):
    for k in range(len(b[0])):
      a[i] += int(b[i][k])
  return a
    # your code here


위에 구현한 row_sum() 함수를 호출하여 반환된 결과값을 출력함.

In [23]:
# 함수 호출
row_sum_list = row_sum(list_b)
# 결과 출력
print("Row sum of list_b: ", row_sum_list)

Row sum of list_b:  [190, 590, 990, 1390, 1790]


# Problem 2 (5 points)
## 아래 주어진 NumPy의 array_c와 array_d를 갖고 문제 1의 순서대로 NumPy배열을 리스트로 변환한 후 np.max()와 같은 계산을 수행하는 find_max(), find_column_max(), find_row_max() 세개의 함수를 작성하시오. np.max() 와 구현한 함수로 부터 얻은 결과값을 비교하시오.

In [24]:
array_c = np.random.random(2000000)
print(array_c)

[0.17574759 0.82927464 0.86275375 ... 0.41372316 0.35212333 0.45082181]


## Problem 2-1

In [25]:
max_array = np.max(array_c)
print("Maximum value in array_c: ", max_array)

Maximum value in array_c:  0.9999998389012089


In [26]:
"""
이 셀 안에 코드를 작성하시오.
"""
# 함수 작성
def find_max(c):
  max=-1
  for i in c:
    if(max<i): max=i
  return max
    # your code here


In [27]:
# NumPy배열에서 리스트로 변환
list_c = array_c.tolist()

In [28]:
# 리스트를 입력값으로 하는 find_max() 함수 호출하여 결과값을 출력
max_list = find_max(list_c)
print("Maximum value in list_c: ", max_list)

Maximum value in list_c:  0.9999998389012089


## Problem 2-2

In [29]:
array_d = array_c.reshape(2000,1000)
print(array_d)

[[0.17574759 0.82927464 0.86275375 ... 0.09486241 0.47958326 0.22187051]
 [0.36711052 0.91660555 0.64933144 ... 0.78310896 0.74617375 0.85660395]
 [0.22680399 0.4895144  0.76102448 ... 0.50514431 0.13479188 0.66353363]
 ...
 [0.57623731 0.02772481 0.13716615 ... 0.82950901 0.4243386  0.69023405]
 [0.85840577 0.85397024 0.8795994  ... 0.45356659 0.90045566 0.830896  ]
 [0.97831884 0.963244   0.51824543 ... 0.41372316 0.35212333 0.45082181]]


In [30]:
column_max_array = np.max(array_d, axis=0)
print("Maximum value of each column in array_d: ", column_max_array)

Maximum value of each column in array_d:  [0.9994653  0.99946097 0.99817642 0.99994068 0.99845832 0.99997535
 0.99882575 0.999218   0.9997988  0.99989201 0.99989675 0.99992879
 0.99981193 0.99954106 0.9998173  0.99988501 0.99986232 0.99949292
 0.99998162 0.99996986 0.99948728 0.99962597 0.99998771 0.99970378
 0.99895092 0.9996439  0.9992847  0.99948016 0.99989733 0.99997926
 0.99999005 0.99995384 0.99928382 0.99914253 0.99989677 0.99998424
 0.99999424 0.99972395 0.99962206 0.99996122 0.99969397 0.99940883
 0.99992666 0.99950369 0.99989162 0.99941959 0.99958037 0.99996784
 0.99946056 0.99980193 0.99956209 0.99994184 0.99944476 0.99878203
 0.99994744 0.99971933 0.99998544 0.99998043 0.99985221 0.99966156
 0.99885575 0.99990981 0.99998973 0.99974591 0.99992358 0.99968428
 0.9997636  0.99865169 0.9999642  0.99977176 0.99994142 0.99958985
 0.99990428 0.99935846 0.9993784  0.99968894 0.99918326 0.99963441
 0.99957398 0.99993628 0.99974561 0.99964897 0.99982025 0.99989926
 0.99928168 0.998652

In [31]:
"""
이 셀 안에 코드를 작성하시오.
"""
# 함수 작성
def find_column_max(d):
  a=[0 for i in range(10)]
  for i in range(10):
    max=-1
    for j in range(20):
      if(d[j][i]>max): max=d[j][i]
    a[i]=max


  return a
    # your code here


In [32]:
# NumPy배열에서 리스트로 변환
list_d = array_d.tolist()

In [33]:
# 리스트를 입력값으로 하는 find_column_max() 함수 호출하여 결과값을 출력
column_max_list = find_column_max(list_d)
print("Maximum value of each column in list_d: ", column_max_list)

Maximum value of each column in list_d:  [0.9709038962005645, 0.9801525895480475, 0.9932362104729314, 0.9557384559008936, 0.8726262832403603, 0.8972165738100628, 0.9717723659771572, 0.9891563850629654, 0.9662420371584233, 0.8549120394579383]


## Problem 2-3

In [34]:
row_max_array = np.max(array_d, axis=1)
print("Maximum value of each row in array_d: ", row_max_array)

Maximum value of each row in array_d:  [0.99899787 0.99948229 0.99733184 ... 0.99912838 0.9993784  0.99998162]


In [35]:
"""
이 셀 안에 코드를 작성하시오.
"""
# 함수 작성
def find_row_max(d):
  a=[0 for i in range(20)]
  for i in range(20):
    max=-1
    for k in d[i]:
      if(max<k): max=k
    a[i]=max


  return a
    # your code here


In [36]:
# 리스트를 입력값으로 하는 find_row_max() 함수 호출하여 결과값을 출력
row_max_list = find_row_max(list_d)
print("Maximum value of each row in list_d: ", row_max_list)

Maximum value of each row in list_d:  [0.9989978713668647, 0.9994822912538578, 0.9973318384079723, 0.9997815147704158, 0.9992456984967757, 0.999333900163677, 0.9983205311811375, 0.9999116103926005, 0.9999809895015703, 0.9995491022176758, 0.9938969012360535, 0.9981617110652732, 0.998277185132498, 0.9996724557248122, 0.9993067312738763, 0.9990997506627687, 0.9977142042951488, 0.9994157855658681, 0.9966987732574597, 0.9984965992426283]


# Problem 3 (1 point)
## NumPy에서 제공되는 함수(예: np.sum(), np.max() )와 list를 이용하여 직접 구현한 함수 (total_sum(), column_sum(), row_sum(), find_max(), find_column_max(), find_row_max() )의 실행 속도를 측정하여 비교하시오. (보충 설명: 위 Problem 1과 Problem 2에서 각각의 함수가 호출되어 실행된 셀안에서 실행시간을 측정하시오.)
(참고: %time 명령을 이용하거나(option 1) 아래 코드를 참고해서(option 2) 실행시간을 측정하시오.)

In [37]:
%time # option 1

print("")

import time # option 2
start = time.time()
# 코드 실행
print("hello")
end = time.time()
print(end - start)

CPU times: total: 0 ns
Wall time: 0 ns

hello
0.0


### 함수들의 실행시간을 비교하여 얻은 결과를 바탕으로 결론을 요약해서 작성하시오.
#### (Markdown 과 Code를 활용하여 자유형식으로 아래에 결론을 작성 (셀 추가 가능) )
#### 배열의 크기를 더 확장시켜 실행 시간을 비교하는 것을 권장함.

실행 속도: Numpy에서 제공된 함수의 속도>직접 만든 함수

결론: 데이터의양이 적을때는 직접만든 함수가 빠르지만 1000000을 넘을 정도로 데이터가 커지면 numpy에서 제공하는 함수가 더 빠르다.


In [39]:
import time
array_a=np.arange(15000000)
start1=time.time()

sum_a=np.sum(array_a)
max_a=np.max(list_c)
p1=np.sum(array_b, axis=1)
q1=np.sum(array_b, axis=0)
e1=np.max(array_d, axis=1)
d1=np.max(array_d, axis=0)

end1=time.time()

start2=time.time()

sum_a2=total_sum(array_a)
p=column_sum(list_b)
q=row_sum(list_b)
k=find_max(list_c)
d=find_column_max(list_d)
e=find_row_max(list_d)

end2=time.time()

print(end1-start1)
print(end2-start2)



C:\Users\김민준\AppData\Local\Temp\ipykernel_9252\3523957093.py:8: RuntimeWarning: overflow encountered in scalar add
  sum+=i


0.10142707824707031
1.01320219039917
